// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Connack message and its fields.

#pragma once

#include "mqttsn/field/ReturnCodeCommon.h"

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref mqttsn::message::Connack message.
/// @see mqttsn::message::ConnackFields
struct ConnackFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqttsn::message::ConnackFields::ReturnCode field.
    using ReturnCodeCommon = mqttsn::field::ReturnCodeCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqttsn::message::Connack message.
/// @see mqttsn::message::Connack
struct ConnackCommon
{
    /// @brief Name of the @ref mqttsn::message::Connack message.
    static const char* name()
    {
        return "CONNACK";
    }
    
};

} // namespace message

} // namespace mqttsn


