// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Willtopicresp message and its fields.

#pragma once

#include "mqttsn/field/ReturnCodeCommon.h"

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref mqttsn::message::Willtopicresp message.
/// @see mqttsn::message::WilltopicrespFields
struct WilltopicrespFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqttsn::message::WilltopicrespFields::ReturnCode field.
    using ReturnCodeCommon = mqttsn::field::ReturnCodeCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqttsn::message::Willtopicresp message.
/// @see mqttsn::message::Willtopicresp
struct WilltopicrespCommon
{
    /// @brief Name of the @ref mqttsn::message::Willtopicresp message.
    static const char* name()
    {
        return "WILLTOPICRESP";
    }
    
};

} // namespace message

} // namespace mqttsn


