// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Pingresp message and its fields.

#pragma once

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqttsn::message::Pingresp message.
/// @see mqttsn::message::Pingresp
struct PingrespCommon
{
    /// @brief Name of the @ref mqttsn::message::Pingresp message.
    static const char* name()
    {
        return "PINGRESP";
    }
    
};

} // namespace message

} // namespace mqttsn


