// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::message::Willmsgreq message and its fields.

#pragma once

namespace mqttsn
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqttsn::message::Willmsgreq message.
/// @see mqttsn::message::Willmsgreq
struct WillmsgreqCommon
{
    /// @brief Name of the @ref mqttsn::message::Willmsgreq message.
    static const char* name()
    {
        return "WILLMSGREQ";
    }
    
};

} // namespace message

} // namespace mqttsn


