// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::WillMsg field.

#pragma once

namespace mqttsn
{

namespace field
{

/// @brief Scope for all the common definitions of the
///     @ref mqttsn::field::WillMsg field.
struct WillMsgCommon
{
    /// @brief Name of the @ref mqttsn::field::WillMsg field.
    static const char* name()
    {
        return "WillMsg";
    }
    
};


} // namespace field

} // namespace mqttsn


