// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::MsgId field.

#pragma once

#include <algorithm>
#include <cstdint>
#include <iterator>
#include <utility>
#include "mqttsn/MsgId.h"

namespace mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqttsn::field::MsgId field.
struct MsgIdCommon
{
    /// @brief Values enumerator for
    ///     @ref mqttsn::field::MsgId field.
    using ValueType = mqttsn::MsgId;
    
    /// @brief Name of the @ref mqttsn::field::MsgId field.
    static const char* name()
    {
        return "MsgId";
    }
    
    /// @brief Retrieve name of the enum value
    static const char* valueName(mqttsn::MsgId val)
    {
        using NameInfo = std::pair<mqttsn::MsgId, const char*>;
        static const NameInfo Map[] = {
            std::make_pair(mqttsn::MsgId_Advertise, "ADVERTISE"),
            std::make_pair(mqttsn::MsgId_Searchgw, "SEARCHGW"),
            std::make_pair(mqttsn::MsgId_Gwinfo, "GWINFO"),
            std::make_pair(mqttsn::MsgId_Connect, "CONNECT"),
            std::make_pair(mqttsn::MsgId_Connack, "CONNACK"),
            std::make_pair(mqttsn::MsgId_Willtopicreq, "WILLTOPICREQ"),
            std::make_pair(mqttsn::MsgId_Willtopic, "WILLTOPIC"),
            std::make_pair(mqttsn::MsgId_Willmsgreq, "WILLMSGREQ"),
            std::make_pair(mqttsn::MsgId_Willmsg, "WILLMSG"),
            std::make_pair(mqttsn::MsgId_Register, "REGISTER"),
            std::make_pair(mqttsn::MsgId_Regack, "REGACK"),
            std::make_pair(mqttsn::MsgId_Publish, "PUBLISH"),
            std::make_pair(mqttsn::MsgId_Puback, "PUBACK"),
            std::make_pair(mqttsn::MsgId_Pubcomp, "PUBCOMP"),
            std::make_pair(mqttsn::MsgId_Pubrec, "PUBREC"),
            std::make_pair(mqttsn::MsgId_Pubrel, "PUBREL"),
            std::make_pair(mqttsn::MsgId_Subscribe, "SUBSCRIBE"),
            std::make_pair(mqttsn::MsgId_Suback, "SUBACK"),
            std::make_pair(mqttsn::MsgId_Unsubscribe, "UNSUBSCRIBE"),
            std::make_pair(mqttsn::MsgId_Unsuback, "UNSUBACK"),
            std::make_pair(mqttsn::MsgId_Pingreq, "PINGREQ"),
            std::make_pair(mqttsn::MsgId_Pingresp, "PINGRESP"),
            std::make_pair(mqttsn::MsgId_Disconnect, "DISCONNECT"),
            std::make_pair(mqttsn::MsgId_Willtopicupd, "WILLTOPICUPD"),
            std::make_pair(mqttsn::MsgId_Willtopicresp, "WILLTOPICRESP"),
            std::make_pair(mqttsn::MsgId_Willmsgupd, "WILLMSGUPD"),
            std::make_pair(mqttsn::MsgId_Willmsgresp, "WILLMSGRESP")
        };
        
        auto iter = std::lower_bound(
            std::begin(Map), std::end(Map), val,
            [](const NameInfo& info, mqttsn::MsgId v) -> bool
            {
                return info.first < v;
            });
        
        if ((iter == std::end(Map)) || (iter->first != val)) {
            return nullptr;
        }
        
        return iter->second;
    }
    
};

/// @brief Values enumerator for
///     @ref mqttsn::field::MsgId field.
using MsgIdVal = MsgIdCommon::ValueType;

} // namespace field

} // namespace mqttsn


