// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::Radius field.

#pragma once

#include <cstdint>

namespace mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqttsn::field::Radius field.
struct RadiusCommon
{
    /// @brief Re-definition of the value type used by
    ///     mqttsn::field::Radius field.
    using ValueType = std::uint8_t;

    /// @brief Name of the @ref mqttsn::field::Radius field.
    static const char* name()
    {
        return "Radius";
    }
    
    /// @brief Special value <b>"BroadcastToAll"</b>.
    static constexpr ValueType valueBroadcastToAll()
    {
        return static_cast<ValueType>(0);
    }
    
    
    
};

} // namespace field

} // namespace mqttsn


