// Generated by commsdsl2comms v3.4.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqttsn::field::ReturnCode field.

#pragma once

#include <cstdint>
#include <type_traits>

namespace mqttsn
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqttsn::field::ReturnCode field.
struct ReturnCodeCommon
{
    /// @brief Values enumerator for
    ///     @ref mqttsn::field::ReturnCode field.
    enum class ValueType : std::uint8_t
    {
        Accepted = 0, ///< value @b Accepted
        Congestion = 1, ///< value @b Congestion
        InvalidTopicId = 2, ///< value @b InvalidTopicId
        NotSupported = 3, ///< value @b NotSupported
        
        // --- Extra values generated for convenience ---
        FirstValue = 0, ///< First defined value.
        LastValue = 3, ///< Last defined value.
        ValuesLimit = 4, ///< Upper limit for defined values.
        
    };
    
    /// @brief Name of the @ref mqttsn::field::ReturnCode field.
    static const char* name()
    {
        return "ReturnCode";
    }
    
    /// @brief Retrieve name of the enum value
    static const char* valueName(ValueType val)
    {
        static const char* Map[] = {
            "Accepted",
            "Congestion",
            "InvalidTopicId",
            "NotSupported"
        };
        static const std::size_t MapSize = std::extent<decltype(Map)>::value;
        
        if (MapSize <= static_cast<std::size_t>(val)) {
            return nullptr;
        }
        
        return Map[static_cast<std::size_t>(val)];
    }
    
};

/// @brief Values enumerator for
///     @ref mqttsn::field::ReturnCode field.
using ReturnCodeVal = ReturnCodeCommon::ValueType;

} // namespace field

} // namespace mqttsn


